version = 0.1

[default.global.parameters]
stack_name = "botmaker-webhook-ingestion"

[default.build.parameters]
cached = true
parallel = true
use_container = true

[default.validate.parameters]
lint = true

[default.deploy.parameters]
region = "us-east-1"
confirm_changeset = true
s3_bucket = "mecubro-chat-develop"
fail_on_empty_changeset = false
parameter_overrides = "Environment=dev LogLevel=INFO DbHost=mecubrochatdev-dc1f5878.ct5618n6bomg.us-east-1.rds.amazonaws.com DbPort=3306 DbName=mecubrochatdev DbUser=admin"

[default.local_start_api.parameters]
warm_containers = "EAGER"
parameter_overrides = "Environment=dev LogLevel=INFO DbHost=mecubrochatdev-dc1f5878.ct5618n6bomg.us-east-1.rds.amazonaws.com DbPort=3306 DbName=mecubrochatdev DbUser=admin"
